/*
 * ArcEmu MMORPG Server
 * Copyright (C) 2005-2007 Ascent Team <http://www.ascentemu.com/>
 * Copyright (C) 2008-2012 <http://www.ArcEmu.org/>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

#ifndef __MAP_H
#define __MAP_H

enum MapNames
{
	/// World of Warcraft
	// Eastern Kingdoms
	MAP_BLASTED_LANDS						= 4,
	MAP_SWAMP_OF_SORROWS					= 8,
	MAP_BLACKROCK_MOUNTAIN					= 25,
	MAP_DEADWIND_PASS						= 41,
	MAP_BURNING_STEPPES						= 46,
	MAP_SEARING_GORGE						= 51,
	MAP_BADLANDS							= 3,
	MAP_EASTERN_PLAGUELANDS					= 139,
	MAP_WESTERN_PLAGUELANDS					= 28,
	MAP_STRANGLETHORN_VALE					= 33,
	MAP_THE_HINTERLANDS						= 47,
	MAP_ARATHI_HIGHLANDS					= 45,
	MAP_DUSKWOOD							= 10,
	MAP_WETLANDS							= 11,
	MAP_HILLSBRAD_FOOTHILLS					= 267,
	MAP_REDRIDGE_MOUNTAINS					= 44,
	MAP_LOCH_MODAN							= 38,
	MAP_SILVERPINE_FOREST					= 130,
	MAP_WESTFALL							= 40,
	MAP_ELWYNN_FOREST						= 12,
	MAP_DUN_MOROGH							= 1,
	MAP_TIRISFAL_GLADES						= 85,
	MAP_DEEPRUN_TRAM						= 2257,
	BG_ALTERAC_VALLEY						= 2597,
	BG_ARATHI_BASIN							= 3358,
	CITY_IRONFORGE							= 1537,
	CITY_STORMWIND_CITY						= 1519,
	CITY_UNDERCITY							= 1497,
	DUNGEON_SCHOLOMANCE						= 2057,
	DUNGEON_SCARLET_MONASTERY_CATHEDRAL		= 796,
	DUNGEON_SCARLET_MONASTERY_ARMORY		= 796,
	DUNGEON_SCARLET_MONASTERY_LIBRARY		= 796,
	DUNGEON_SCARLET_MONASTERY_GRAVEYARD		= 796,
	DUNGEON_BLACKROCK_SPIRE					= 1583,
	DUNGEON_BLACKROCK_DEPTHS				= 1584,
	DUNGEON_SUNKEN_TEMPLE					= 1477,
	DUNGEON_STRATHOLME						= 2017,
	DUNGEON_ULDAMAN							= 1337,
	DUNGEON_GNOMEREGAN						= 721,
	DUNGEON_THE_STOCKADE					= 717,
	DUNGEON_SHADOWFANG_KEEP					= 209,
	DUNGEON_THE_DEADMINES					= 1581,
	RAID_BLACKWING_LAIR						= 2677,
	RAID_MOLTEN_CORE						= 2717,
	// Kalimdor
	MAP_SILITHUS							= 1377,
	MAP_UNGORO_CRATER						= 490,
	MAP_WINTERSPRING						= 618,
	MAP_FELWOOD								= 361,
	MAP_TANARIS								= 440,
	MAP_THOUSAND_NEEDLES					= 400,
	MAP_DUSTWALLOW_MARSH					= 15,
	MAP_FERALAS								= 357,
	MAP_DESOLACE							= 405,
	MAP_STONETALON_MOUNTAINS				= 406,
	MAP_ASHENVALE							= 331,
	MAP_MOONGLADE							= 493,
	MAP_DARKSHORE							= 148,
	MAP_AZSHARA								= 16,
	MAP_BARRENS								= 17,
	MAP_TELDRASSIL							= 141,
	MAP_DUROTAR								= 14,
	MAP_MULGORE								= 215,
	MAP_GM_ISLAND							= 876,
	MAP_THE_VEILED_SEA						= 457,
	BG_WARSONG_GULCH						= 3277,
	CITY_ORGRIMMAR							= 1637,
	CITY_THUNDER_BLUFF						= 1638,
	CITY_DARNASSUS							= 1657,
	DUNGEON_ZULFARRAK						= 1176,
	DUNGEON_DIRE_MAUL						= 2557,
	DUNGEON_RAZORFEN_DOWNS					= 722,
	DUNGEON_MARAUDON						= 2100,
	DUNGEON_RAZORFEN_KRAUL					= 491,
	DUNGEON_BLACKFATHOM_DEEPS				= 719,
	DUNGEON_WAILING_CAVERNS					= 718,
	DUNGEON_RAGEFIRE_CHASM					= 2437,
	RAID_RUINS_OF_AHNQIRAJ					= 3429,
	RAID_TEMPLE_OF_AHNQIRAJ					= 3428,

	/// The Burning Crusade
	// Eastern Kingdoms
	MAP_EVERSONG_WOODS				= 3430,
	MAP_GHOSTLANDS					= 3433,
	ARENA_RUINS_OF_LORDAERON		= 3968,
	CITY_SILVERMOON_CITY			= 3487,
	RAID_KARAZHAN					= 3457,
	RAID_SUNWELL_PLATEAU			= 4075,
	// Kalimdor
	MAP_BLOODMYST_ISLE				= 3525,
	MAP_AZUREMYST_ISLE				= 3524,
	MAP_ISLE_OF_QUELDANAS			= 4080,
	CITY_THE_EXODAR					= 3557,
	DUNGEON_THE_BLACK_MORASS		= 2366,
	DUNGEON_OLD_HILLSBRAD_FOOTHILLS	= 2367,
	RAID_HYJAL_SUMMIT				= 3606,
	// Outland
	MAP_SHADOWMOON_VALLEY			= 3520,
	MAP_NETHERSTORM					= 3523,
	MAP_BLADES_EDGE_MOUNTAINS		= 3522,
	MAP_NAGRAND						= 3518,
	MAP_TEROKKAR_FOREST				= 3519,
	MAP_ZANGARMARSH					= 3521,
	MAP_HELLFIRE_PENINSULA			= 3483,
	ARENA_BLADES_EDGE_ARENA			= 3702,
	ARENA_NAGRAND_ARENA				= 3698,
	BG_EYE_OF_THE_STORM				= 3820,
	CITY_SHATTRATH_CITY				= 3703,
	DUNGEON_THE_ARCATRAZ			= 3848,
	DUNGEON_SHADOW_LABYRINTH		= 3789,
	DUNGEON_THE_BOTANICA			= 3847,
	DUNGEON_MAGISERS_TERRACE		= 4131,
	DUNGEON_THE_MECHANAR			= 3849,
	DUNGEON_THE_SHATTERED_HALLS		= 3714,
	DUNGEON_THE_STEAMVAULT			= 3715,
	DUNGEON_SETHEKK_HALLS			= 3791,
	DUNGEON_AUCHENAI_CRYPTS			= 3790,
	DUNGEON_MANA_TOMBS				= 3792,
	DUNGEON_THE_UNDERBOG			= 3716,
	DUNGEON_THE_SLAVE_PENS			= 3717,
	DUNGEON_THE_BLOOD_FURNACE		= 3713,
	DUNGEON_HELLFIRE_RAMPARTS		= 3562,
	RAID_BLACK_TEMPLE				= 3959,
	RAID_GRUULS_LAIR				= 3923,
	RAID_MAGTHERIDONS_LAIR			= 3836,
	RAID_SERPENTSHRINE_CAVERN		= 3607,
	RAID_THE_EYE					= 3845,

	/// Wrath of the Lich King
	// Eastern Kingdoms
	MAP_PLAGUELANDS_THE_SCARLET_ENCLAVE	= 4298,
	// Kalimdor
	ARENA_THE_RING_OF_VALOR				= 4406,
	DUNGEON_THE_CULLING_OF_STRATHOLME	= 4100,
	RAID_ONYXIAS_LAIR					= 2159,
	// Northrend
	MAP_CRYSTALSONG_FOREST				= 2817,
	MAP_WINTERGRASP						= 4197,
	MAP_HROTHGARS_LANDING				= 4742,
	MAP_ICECROWN						= 210,
	MAP_THE_STORM_PEAKS					= 67,
	MAP_SHOLAZAR_BASIN					= 3711,
	MAP_ZULDRAK							= 66,
	MAP_GRIZZLY_HILLS					= 394,
	MAP_DRAGON_BLIGHT					= 65,
	MAP_BOREAN_TUNDRA					= 3537,
	MAP_HOWLING_FJORD					= 495,
	ARENA_DALARAN_ARENA					= 4378,
	BG_ISLE_OF_CONQUEST					= 4710,
	BG_STRAND_OF_THE_ANCIENTS			= 4384,
	CITY_DALARAN						= 4395,
	DUNGEON_THE_FORGE_OF_SOULS			= 4809,
	DUNGEON_PIT_OF_SARON				= 4813,
	DUNGEON_HALLS_OF_REFLECTION			= 4820,
	DUNGEON_HALLS_OF_LIGHTNING			= 4272,
	DUNGEON_THE_OCULUS					= 4228,
	DUNGEON_UTGARDE_PINNACLE			= 1196,
	DUNGEON_TRIAL_OF_THE_CHAMPION		= 4723,
	DUNGEON_HALLS_OF_STONE				= 4264,
	DUNGEON_GUNDRAK						= 4416,
	DUNGEON_THE_VIOLET_HOLD				= 4415,
	DUNGEON_DRAKTHARON_KEEP				= 4196,
	DUNGEON_AHNKAHET_THE_OLD_KINGDOM	= 4494,
	DUNGEON_AZJOL_NERUB					= 4277,
	DUNGEON_THE_NEXUS					= 4265,
	DUNGEON_UTGARDE_KEEP				= 206,
	RAID_VAULT_OF_ARCHAVON				= 4603,
	RAID_TRIAL_OF_THE_CRUSADER			= 4722,
	RAID_THE_EYE_OF_ETERNITY			= 4500,
	RAID_ICECROWN_CITADEL				= 4812,
	RAID_NAXXRAMAS						= 3456,
	RAID_THE_OBSIDIAN_SANCTUM			= 4493,
	RAID_ULDUAR							= 4273,
	RAID_THE_RUBY_SANCTUM				= 4987,

	/// Cataclysm
	// Eastern Kingdoms
	//MAP_RUINS_OF_GILNEAS					= 4706,
	//MAP_GILNEAS								= 4714,
	//MAP_GILNEAS_CITY						= 4755,
	//BG_THE_BATTLE_OF_GILNEAS				= 5449,
	//BG_TWIN_PEAKS							= 5031,
	DUNGEON_ZULGURUB						= 1977,
	DUNGEON_ZULAMAN							= 3805,
	//DUNGEON_GRIM_BATOL						= 4950,
	//DUNGEON_ABYSSAL_MAW_THRONE_OF_THE_TIDES	= 5004,
	//DUNGEON_THRONE_OF_THE_TIDES				= 5004,
	//DUNGEON_BLACKROCK_CAVERNS				= 4926,
	//RAID_BARADIN_HOLD						= 5600,
	//RAID_BLACKWING_DESCENT					= 5094,
	//RAID_THE_BASTION_OF_TWILIGHT			= 5334,
	// Kalimdor
	//MAP_MOLTEN_FRONT						= 5733,
	//MAP_ULDUM								= 5034,
	//MAP_MOUNT_HYJAL						= 616,
	//MAP_AHNQIRAJ_THE_FALLEN_KINGDOM			= 5695,
	//MAP_NORTHERN_BARRENS					= 17,
	//MAP_SOUTHERN_BARRENS					= 4709,
	//MAP_TWILIGHT_HIGHALANDS					= 4922,
	//MAP_VASHJIR_ABYSSAL_DEPTHS				= 5145,
	//MAP_VASHJIR_SHIMMERING_EXPANSE			= 5144,
	//MAP_VASHJIR								= 4146,
	//MAP_THE_STRANGLETHORN_VALE				= 5339,
	//MAP_THE_CAPE_OF_STRANGLETHORN			= 5287,
	//MAP_NORTHERN_STRANGLETHORN				= 33,
	//DUNGEON_WELL_OF_ETERNITY				= 5788,
	//DUNGEON_HALLS_OF_ORIGINATION			= 4945,
	//DUNGEON_END_TIME						= 5789,
	//DUNGEON_HOUR_OF_TWILIGHT				= 5844,
	//DUNGEON_LOST_CITY_OF_THE_TOLVIR			= 5396,
	//DUNGEON_THE_VORTEX_PINNACLE				= 5035,
	//RAID_FIRELANDS							= 5723,
	//RAID_THRONE_OF_THE_FOUR_WINDS			= 5638,
	// The Maelstrom
	//MAP_TOL_BARAD_PENINSULA					= 5389,
	//MAP_TOL_BARAD							= 5095,
	//MAP_DEEPHOLM							= 5042,
	//MAP_DARKMOON_ISLAND						= 5861,
	//CITY_DARKMOON_ISLAND					= 5861,
	//MAP_THE_LOST_ISLES						= 4720,
	//MAP_KEZAN								= 4737,
	//MAP_THE_MAELSTROM						= 5416,
	//DUNGEON_THE_STONECORE					= 5088,

	/// Mists of Pandaria
	// Eastern Kingdoms
	//DUNGEON_SCHOLOMANCE_UPDATE			= 6066,
	//DUNGEON_SCARLET_MONASTERY			= 6109,
	//DUNGEON_SCARLET_HALLS				= 6052,
	// Kalimdor
	//MAP_AMMEN_VALE						= 6456,
	//MAP_SHADOWGLEN						= 6450,
	//MAP_ECHO_ISLES						= 6453,
	//MAP_CAMP_NARACHE					= 6452,
	//MAP_VALLEY_OF_TRIALS				= 6451,
	//MAP_COLDRIDGE_VALLEY				= 6176,
	//MAP_NORTHSHIRE						= 6170,
	//MAP_NEW_TINKERTOWN					= 6457,
	//MAP_DEATHKNELL						= 6454,
	//MAP_SUNSTRIDER_ISLE					= 6455,
	//ARENA_TOLVIRON_ARENA				= 6296,
	// The Maelstrom
	//MAP_THE_WANDERING_ISLE				= 5736,
	// Pandaria
	//SCENARIO_THERAMORES_FALL_A			= 6500,
	//SCENARIO_ARENA_OF_ANNIHILATION		= 6219,
	//SCENARIO_ASSAULT_ON_ZANVESS			= 6328,
	//SCENARIO_BATTLE_ON_THE_HIGH_SEAS	= 6567,
	//SCENARIO_BLOOD_IN_THE_SNOW			= 6678,
	//MAP_VALE_OF_ETERNAL_BLOSSOMS		= 5840,
	//SCENARIO_A_BREWING_STORM			= 6101,
	//SCENARIO_BREWMOON_FESTIVAL			= 6426,
	//SCENARIO_DAGGER_IN_THE_DARK			= 6565,
	//SCENARIO_DOMINATION_POINT			= 6615,
	//SCENARIO_FALL_OF_SHAN_BU			= 6677,
	//SCENARIO_CRYPT_OF_FORGOTTEN_KINGS	= 6208,
	//MAP_ISLE_OF_GIANTS					= 6661,
	//SCENARIO_GREENSTONE_VILLAGE			= 6209,
	//SCENARIO_PROVING_GROUNDS			= 6852,
	//SCENARIO_UNGA_INGOO					= 6309,
	//SCENARIO_THE_SECRET_INGREDIENT		= 6863,
	//SCENARIO_LIONS_LANDING				= 6575,
	//SCENARIO_DARK_HEART_OF_PANDARIA		= 6733,
	//SCENARIO_A_LITTLE_PATIENCE			= 6616,
	//SCENARIO_PURSUING_THE_BLACK_HARVEST	= 6613,
	//SCENARIO_THE_SECRETS_OF_RAGEFIRE	= 6731,
	//MAP_THE_SITUATION_IN_DALARAN		= 6611,
	//SCENARIO_TO_THE_SKIES				= 6673,
	//SCENARIO_STORMSEA_LANDING			= 6666,
	//SCENARIO_THE_THUNDER_FORGE			= 6675,
	//MAP_ISLE_OF_THUNDER					= 6507,
	//SCENARIO_TROVES_OF_THUNDER_KING		= 6716,
	//MAP_TIMELESS_ISLE					= 6757,
	//SCENARIO_CELESTIAL_TOURNAMENT		= 6771,
	//SCENARIO_THERAMORES_FALL_H			= 6040,
	//MAP_DREAD_WASTES					= 6138,
	//MAP_TOWNLONG_STEPPES				= 5842,
	//MAP_THE_VEILED_STAIR				= 6006,
	//MAP_KRASARANG_WILDS					= 6134,
	//MAP_KUN_LAI_SUMMIT					= 5841,
	//MAP_VALLEY_OF_THE_FOUR_WINDS		= 5805,
	//MAP_THE_JADE_FOREST					= 5785,
	//SCENARIO_PEAK_OF_SERENITY			= 6419,
	//ARENA_THE_TIGERS_PEAK				= 6732,
	//BG_DEEPWIND_GORGE					= 6665,
	//BG_TEMPLE_OF_KOTMOGU				= 6051,
	//BG_SILVERSHARD_MINES				= 6126,
	//DUNGEON_GATE_OF_THE_SETTING_SUN		= 5976,
	//DUNGEON_SIEGE_OF_NIUZAO_TEMPLE		= 6214,
	//DUNGEON_MOGUSHAN_PALACE				= 6182,
	//DUNGEON_SHADO_PAN_MONASTERY			= 5918,
	//DUNGEON_TEMPLE_OF_THE_JADE_SERPENT	= 5956,
	//DUNGEON_STORMSTOUT_BREWERY			= 5963,
	//RAID_TERRACE_OF_ENDLESS_SPRING		= 6067,
	//RAID_HEART_OF_FEAR					= 6297,
	//RAID_MOGUSHAN_VAULTS				= 6125,
	//RAID_SIEGE_OF_ORGRIMMAR				= 6738,
	//RAID_THRONE_OF_THUNDER				= 6622,

	/// Warlords of Draenor
	// Eastern Kingdoms
	//MAP_BLASTED_LANDS_DO_NOT_USE		= 6936,
	//BG_HILLSBRAD_FOOTHILLS				= 7107,
	// Draenor
	//MAP_FARALOHN						= 6756,
	//MAP_NAGRAND_DRAENOR					= 6755,
	//MAP_TALADOR							= 6662,
	//MAP_GORGROND						= 6721,
	//MAP_SPIRES_OF_ARAK					= 6722,
	//MAP_FROSTFIRE_RIDGE					= 6720,
	//MAP_SHADOWMOON_VALLEY_DRAENOR		= 6719,
	//MAP_DEFENSE_OF_KARABOR				= 7083,
	//MAP_FROSTWALL						= 7004,
	//MAP_GREAT_HALL						= 7230,
	//MAP_TOWN_HALL						= 7229,
	//MAP_TANAAN_JUNGLE					= 6723,
	//MAP_LUNARFALL						= 7078,
	//MAP_SHATTRATH_CITY					= 6980,
	//MAP_HEROES_THROUGH_TIME				= 6908,
	//MAP_ASHRAN_TRANSITION_ZONE			= 6975,
	//MAP_ASHRAN							= 6941,
	//MAP_DEFENSE_OF_KARABOR			= 7083,
	//CITY_STORMSHIELD					= 7332,
	//CITY_WARSPEAR						= 7333,
	//DUNGEON_AUCHINDOUN					= 6912,
	//DUNGEON_UPPER_BLACKROCK_SPIRE_WOD	= 7307,
	//DUNGEON_BLOODMAUL_SLAG_MINES		= 6874,
	//DUNGEON_IRON_DOCKS					= 6951,
	//DUNGEON_THE_EVERBLOOM				= 7109,
	//DUNGEON_GRIMRAIL_DEPOT				= 6984,
	//DUNGEON_SHADOWMOON_BURIAL_GROUNDS	= 6932,
	//DUNGEON_SKYREACH					= 6988,
	//DUNGEON_GRIMRAIL_CRASH_SITE			= 7423,
	//DUNGEON_REMAINS_OF_XANDROS			= 7053,
	//RAID_BLACKROCK_FOUNDRY				= 6967,
	//RAID_HIGHMAUL						= 6996,
	//SCENARIO_BONETOWN_SCENARIO			= 6955,
	//SCENARIO_THE_TRIAL_OF_FAITH			= 7381,
	//SCENARIO_FROSTFIRE_RIDGE			= 6960,
	//SCENARIO_GROMMAR					= 6851,
	//SCENARIO_THE_COLISEUM				= 7462,
};

class MapMgr;
struct MapInfo;
class TerrainMgr;

#include "TerrainMgr.h"

struct Formation;

typedef struct
{
	uint32	id;//spawn ID
	uint32	entry;
	float	x;
	float	y;
	float	z;
	float	o;
	Formation* form;
	uint8 movetype;
	uint32 displayid;
	uint32 factionid;
	uint32 flags;
	uint32 bytes0;
	uint32 bytes1;
	uint32 bytes2;
	uint32 emote_state;
	//uint32 respawnNpcLink;
	uint16 channel_spell;
	uint32 channel_target_go;
	uint32 channel_target_creature;
	uint16 stand_state;
	uint32 death_state;
	uint32 MountedDisplayID;
	uint32 Item1SlotDisplay;
	uint32 Item2SlotDisplay;
	uint32 Item3SlotDisplay;
	uint32 CanFly;
	uint32 phase;

	/* sets one of the bytes of an uint32 */
	uint32 setbyte(uint32 buffer, uint8 index, uint32 byte)
	{

		/* We don't want a segfault, now do we? */
		if(index >= 4)
			return buffer;

		byte = byte << index * 8;
		buffer = buffer | byte;

		return buffer;
	}
} CreatureSpawn;

typedef struct
{
	uint32	id;//spawn ID
	uint32	entry;
	float	x;
	float	y;
	float	z;
	float	o;
	float	o1;
	float	o2;
	float	o3;
	float	facing;
	uint32	flags;
	uint32	state;
	uint32	faction;
	//uint32 level;
	float scale;
	//uint32 stateNpcLink;
	uint32 phase;
	uint32 overrides;
} GOSpawn;

typedef std::vector<CreatureSpawn*> CreatureSpawnList;
typedef std::vector<GOSpawn*> GOSpawnList;

typedef struct
{
	CreatureSpawnList CreatureSpawns;
	GOSpawnList GOSpawns;
} CellSpawns;

class SERVER_DECL Map
{
	public:
		Map(uint32 mapid, MapInfo* inf);
		~Map();

		ARCEMU_INLINE string GetNameString() { return name; }
		ARCEMU_INLINE const char* GetName() { return name.c_str(); }
		ARCEMU_INLINE MapEntry* GetDBCEntry() { return me; }

		ARCEMU_INLINE CellSpawns* GetSpawnsList(uint32 cellx, uint32 celly)
		{
			ARCEMU_ASSERT(cellx < _sizeX);
			ARCEMU_ASSERT(celly < _sizeY);
			if(spawns[cellx] == NULL) return NULL;

			return spawns[cellx][celly];
		}
		ARCEMU_INLINE CellSpawns* GetSpawnsListAndCreate(uint32 cellx, uint32 celly)
		{
			ARCEMU_ASSERT(cellx < _sizeX);
			ARCEMU_ASSERT(celly < _sizeY);
			if(spawns[cellx] == NULL)
			{
				spawns[cellx] = new CellSpawns*[_sizeY];
				memset(spawns[cellx], 0, sizeof(CellSpawns*)*_sizeY);
			}

			if(spawns[cellx][celly] == 0)
				spawns[cellx][celly] = new CellSpawns;
			return spawns[cellx][celly];
		}

		void LoadSpawns(bool reload);//set to true to make clean up
		uint32 CreatureSpawnCount;
		uint32 GameObjectSpawnCount;

		ARCEMU_INLINE void CellGoneActive(uint32 x, uint32 y)
		{
		}

		ARCEMU_INLINE void CellGoneIdle(uint32 x, uint32 y)
		{
		}

	private:
		MapInfo* 	   _mapInfo;
		uint32 _mapId;
		string name;
		MapEntry* me;

		//new stuff
		CellSpawns** spawns[_sizeX];
	public:
		CellSpawns staticSpawns;
};

#endif
