#include(${ROOT_PATH}/src/arcemu-shared/git_version.h)

#message("")
#message("* NoxicCore revision: ${BUILD_HASH_STR} ${COMMIT_TIMESTAMP} (${BUILD_BRANCH} branch)")
#message("* NoxicCore buildtype: ${CMAKE_BUILD_TYPE}")
message("")
message("* Visual Studio Compile Heap Limit: ${VISUALSTUDIO_COMPILERHEAPLIMIT}")
message("")
message("* Install core to   : ${CMAKE_INSTALL_PREFIX}")
message("* Install configs to: ${ARCEMU_CONFIGSFILE_PATH}")
message("* Install modules to: ${ARCEMU_SCRIPTLIB_PATH}")
message("* Install tools to  : ${ARCEMU_TOOLS_PATH}")
message("")

IF(BUILD_LOGON)
  message("* Build Logon server: Yes. (Default)")
ELSE()
  message("* Build Logon server: No.")
ENDIF()

IF(BUILD_WORLD)
  message("* Build World server: Yes. (Default)")
ELSE()
  message("* Build World server: No.")
ENDIF()

IF(BUILD_SCRIPTS)
  message("* Build with scripts: Yes. (Default)")
ELSE()
  message("* Build with scripts: No.")
ENDIF()

IF(BUILD_TOOLS)
  message("* Build with tools  : Yes.")
ELSE()
  message("* Build with tools  : No. (Default)")
ENDIF()
message("")